<script setup lang="ts">
import{computed,onActivated,ref,watch}from'vue'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'
const auth=useAuthStore(),isStudent=computed(()=>auth.user?.role==='student'),studentId=ref(auth.user?.id||1),courseId=ref(0),courses=ref<any[]>([]),students=ref<any[]>([]),rows=ref<any[]>([]),path=ref<any>(),profile=ref<any>(),error=ref('')
async function loadCourses(){courses.value=(await api.get('/courses')).data;if(courses.value.length&&!courseId.value)courseId.value=courses.value[0].id}
async function loadStudents(){if(isStudent.value||!courseId.value)return;students.value=(await api.get(`/courses/${courseId.value}/students`)).data;if(students.value.length)studentId.value=students.value[0].id}
async function load(){try{rows.value=(await api.get(`/students/${studentId.value}/mastery`)).data}catch(e:any){error.value=e.message}}
async function generate(){try{path.value=(await api.post(`/students/${studentId.value}/learning-paths/generate?course_id=${courseId.value}`)).data}catch(e:any){error.value=e.message}}
async function loadProfile(){try{profile.value=(await api.get(`/students/${studentId.value}/weak-profile?course_id=${courseId.value}`)).data}catch(e:any){error.value=e.message}}
watch(courseId,()=>loadStudents().catch(e=>error.value=e.message))
onActivated(async()=>{await loadCourses();await loadStudents();if(isStudent.value)await load()})
</script>
<template><div class="page"><div class="page-title"><div><h1>{{isStudent?'我的学习画像':'学生学情分析'}}</h1><p>根据教师确认的作业成绩生成知识点掌握度、薄弱画像和学习内容推荐。</p></div></div><div class="card"><div class="form-grid"><label>课程<select v-model.number="courseId"><option v-for="c in courses" :value="c.id">{{c.name}}</option></select></label><label v-if="!isStudent">学生<select v-model.number="studentId"><option v-for="s in students" :value="s.id">{{s.display_name}}（{{s.username}}）</option></select></label></div><button @click="load">查看掌握度</button> <button class="secondary" @click="loadProfile">生成薄弱知识画像</button> <button class="secondary" @click="generate">生成学习路径</button><p class="error">{{error}}</p></div><div v-if="!rows.length" class="card empty">暂无已确认的学习数据</div><div class="grid"><div v-for="x in rows" class="card"><div class="metric">{{Math.round(x.score*100)}}%</div><p>知识点 {{x.knowledge_point_id}}</p><span :class="['status',x.level==='已掌握'?'approved':'pending_review']">{{x.level}}</span></div></div><div v-if="profile" class="card weak-profile"><div class="section-header"><div><span class="eyebrow">薄弱知识画像</span><h2>{{profile.student.display_name}}</h2></div><span class="badge">{{profile.weak_count}} 个待巩固知识点</span></div><p>{{profile.summary}}</p><div v-if="!profile.weak_points.length" class="empty">当前没有明显薄弱知识点，请继续保持</div><article v-for="point in profile.weak_points" class="weak-point"><div class="section-header"><h3>{{point.name}}</h3><strong>{{Math.round(point.score*100)}}%</strong></div><p>{{point.description||'该知识点需要进一步巩固。'}}</p><h4>推荐学习内容</h4><div v-if="!point.recommendations.length" class="muted">课程知识库中暂未找到直接推荐材料</div><div v-for="rec in point.recommendations" class="recommendation"><strong>{{rec.filename}}</strong><p>{{rec.content_preview}}…</p></div></article></div><div v-if="path" class="card"><h2>个性化学习路径</h2><div v-if="!path.items.length" class="empty">当前知识点掌握良好，暂无补强任务</div><ol><li v-for="item in path.items"><strong>知识点 {{item.knowledge_point_id}}</strong> · 优先级 {{item.priority}}<p>{{item.steps.join(' → ')}}</p></li></ol></div></div></template>
