<script setup lang="ts">
import{computed,onActivated,ref}from'vue'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'
import{useRoute}from'vue-router'

const route=useRoute(),auth=useAuthStore(),isStudent=computed(()=>auth.user?.role==='student')
const studentId=ref(auth.user?.id||1),courseId=Number(route.params.courseId),students=ref<any[]>([]),rows=ref<any[]>([])
const path=ref<any>(),profile=ref<any>(),courseAnalysis=ref<any>(),kgMasteryData=ref<any>(null),error=ref(''),loading=ref(false)
async function loadStudents(){if(isStudent.value)return;students.value=(await api.get(`/courses/${courseId}/students`)).data;if(!students.value.length)studentId.value=0;else if(!students.value.some(x=>x.id===studentId.value))studentId.value=students.value[0].id}
async function load(){if(!studentId.value)return;loading.value=true;error.value='';try{const [mastery,analysis,kgMastery]=await Promise.all([api.get(`/students/${studentId.value}/mastery?course_id=${courseId}`),api.get(`/students/${studentId.value}/course-analysis?course_id=${courseId}`),api.get(`/knowledge-graphs/student-mastery/${studentId.value}/course/${courseId}`).catch(()=>null)]);rows.value=mastery.data;courseAnalysis.value=analysis.data;if(kgMastery&&kgMastery.data){kgMasteryData.value=kgMastery.data}}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function generate(){try{path.value=(await api.post(`/students/${studentId.value}/learning-paths/generate?course_id=${courseId}`)).data}catch(e:any){error.value=e.message}}
async function loadProfile(){try{profile.value=(await api.get(`/students/${studentId.value}/weak-profile?course_id=${courseId}`)).data}catch(e:any){error.value=e.message}}
async function refreshAll(){await load();await loadProfile()}
onActivated(async()=>{try{await loadStudents();await refreshAll()}catch(e:any){error.value=e.message}})
</script>
<template><div class="page analytics-page"><div class="page-title"><div><h1>{{isStudent?'我的学习画像':'学生学情分析'}}</h1><p>综合本课程全部已发布作业（包括已完成和未完成）及课堂答疑情况进行分析。</p></div></div><div class="card"><div class="form-grid"><label v-if="!isStudent">学生<select v-model.number="studentId"><option v-for="s in students" :value="s.id">{{s.display_name}}（{{s.username}}）</option></select></label></div><button :disabled="loading||!studentId" @click="refreshAll">{{loading?'分析中…':'刷新课程学情'}}</button> <button class="secondary" :disabled="!studentId" @click="generate">生成学习路径</button><p class="error">{{error}}</p></div>
<section v-if="courseAnalysis" class="card course-learning-analysis"><div class="section-header"><div><span class="eyebrow">课程参与与完成情况</span><h2>综合分析</h2></div><span :class="['status',courseAnalysis.completion_rate>=.8?'approved':'pending_review']">完成率 {{Math.round(courseAnalysis.completion_rate*100)}}%</span></div><p class="analysis-summary">{{courseAnalysis.summary}}</p><div class="grid analysis-metrics"><div><strong>已发布作业</strong><div class="metric">{{courseAnalysis.assignment_total}}</div></div><div><strong>已完成</strong><div class="metric">{{courseAnalysis.assignment_completed}}</div></div><div><strong>未完成</strong><div class="metric">{{courseAnalysis.assignment_missing}}</div></div><div><strong>课堂提问</strong><div class="metric">{{courseAnalysis.qa_questions}}</div></div></div><h3>逐项作业情况</h3><div v-if="!courseAnalysis.assignments.length" class="empty">当前课程尚未发布作业</div><div v-for="item in courseAnalysis.assignments" :key="item.assignment_id" class="analysis-assignment"><div><strong>{{item.title}}</strong><small v-if="item.due_at">截止 {{new Date(item.due_at).toLocaleString()}}</small></div><span v-if="item.completed" class="status approved">已完成<span v-if="item.score_rate!=null"> · 得分率 {{Math.round(item.score_rate*100)}}%</span></span><span v-else :class="['status',item.overdue?'failed':'pending_review']">{{item.overdue?'逾期未完成':'尚未完成'}}</span></div></section>
<div v-if="!rows.length" class="card empty">本课程暂无已确认的知识点掌握数据</div><div class="grid"><div v-for="x in rows" :key="x.knowledge_point_id" class="card"><div class="metric">{{Math.round(x.score*100)}}%</div><p>知识点 {{x.knowledge_point_id}}</p><span :class="['status',x.level==='已掌握'?'approved':'pending_review']">{{x.level}}</span></div></div>
<div v-if="kgMasteryData" class="card"><h3>知识点图谱掌握度</h3><div v-for="kp in kgMasteryData.knowledge_points" :key="kp.knowledge_point_id" class="mastery-bar"><span>{{kp.knowledge_point_name}}</span><div class="progress-bar"><div :style="{width: kp.accuracy_rate*100+'%'}" :class="kp.level"></div></div><span>{{Math.round(kp.accuracy_rate*100)}}%</span></div><div v-if="kgMasteryData.weak_areas.length" class="notice"><strong>薄弱知识点：</strong>{{kgMasteryData.weak_areas.join('、')}}</div></div>
<div v-if="profile" class="card weak-profile"><div class="section-header"><div><span class="eyebrow">薄弱知识画像</span><h2>{{profile.student.display_name}}</h2></div><span class="badge">{{profile.weak_count}} 个待巩固知识点</span></div><p>{{profile.summary}}</p><div v-if="!profile.weak_points.length" class="empty">当前没有明显薄弱知识点，请继续保持</div><article v-for="point in profile.weak_points" :key="point.knowledge_point_id" class="weak-point"><div class="section-header"><h3>{{point.name}}</h3><strong>{{Math.round(point.score*100)}}%</strong></div><p>{{point.description||'该知识点需要进一步巩固。'}}</p><h4>推荐学习内容</h4><div v-if="!point.recommendations.length" class="muted">课程知识库中暂未找到直接推荐材料</div><div v-for="rec in point.recommendations" :key="rec.chunk_id" class="recommendation"><strong>{{rec.filename}}</strong><p>{{rec.content_preview}}…</p></div></article></div>
<div v-if="path" class="card"><h2>个性化学习路径</h2><div v-if="!path.items.length" class="empty">当前知识点掌握良好，暂无补强任务</div><ol><li v-for="item in path.items" :key="item.knowledge_point_id"><strong>知识点 {{item.knowledge_point_id}}</strong> · 优先级 {{item.priority}}<p>{{item.steps.join(' → ')}}</p></li></ol></div></div></template>
