<script setup lang="ts">
import {computed,onActivated,ref} from 'vue'
import {api} from '../api/client'
import {useAuthStore} from '../stores/auth'

const auth=useAuthStore(),assignments=ref<any[]>([]),courses=ref<any[]>([]),documents=ref<any[]>([])
const selected=ref<any>(),submissions=ref<any[]>([]),selectedSubmission=ref<any>(),answers=ref<Record<number,any>>({})
const tab=ref('list'),error=ref(''),message=ref(''),loading=ref(false)
const isTeacher=computed(()=>['teacher','admin'].includes(auth.user?.role||''))
const groupedAssignments=computed(()=>Object.values(assignments.value.reduce((groups:any,item:any)=>{const key=item.course_id;if(!groups[key])groups[key]={course_id:key,course_name:item.course_name,items:[]};groups[key].items.push(item);return groups},{})) as any[])
const assignmentForm=ref({course_id:0,title:'',description:'',due_at:''})
const questionForm=ref({id:0,question_type:'single_choice',stem:'',standard_answer:'',options_text:'A|选项A\nB|选项B',max_score:5})
const standardSelections=ref<string[]>([])
const materialForm=ref({document_id:0,chapter_or_topic:'',example_count:1,exercise_count:3,thinking_count:1,extension_count:1})

async function load(){assignments.value=(await api.get('/assignments')).data;courses.value=(await api.get(isTeacher.value?'/courses/managed':'/courses')).data;if(!assignmentForm.value.course_id&&courses.value.length)assignmentForm.value.course_id=courses.value[0].id}
async function createAssignment(){loading.value=true;try{const data=(await api.post('/assignments',{...assignmentForm.value,due_at:assignmentForm.value.due_at||null})).data;message.value='作业草稿创建成功，请添加题目';await load();await openAssignment(data.id)}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function openAssignment(id:number){loading.value=true;try{selected.value=(await api.get(`/assignments/${id}`)).data;answers.value={};selected.value.questions.forEach((q:any)=>answers.value[q.id]=q.question_type==='multiple_choice'?[]:'');if(isTeacher.value){submissions.value=(await api.get(`/assignments/${id}/submissions`)).data;documents.value=(await api.get(`/courses/${selected.value.course_id}/documents`)).data;if(documents.value.length&&!documents.value.some(x=>x.id===materialForm.value.document_id))materialForm.value.document_id=documents.value[0].id}tab.value='detail'}catch(e:any){error.value=e.message}finally{loading.value=false}}
function optionLabel(option:any){return option.key||option.option_key}
function parseOptions(){if(questionForm.value.question_type==='true_false')return[{key:'true',content:'正确'},{key:'false',content:'错误'}];if(!['single_choice','multiple_choice'].includes(questionForm.value.question_type))return null;return questionForm.value.options_text.split('\n').filter(Boolean).map(line=>{const [key,...rest]=line.split('|');return{key:key.trim(),content:rest.join('|').trim()}}).filter(x=>x.key&&x.content)}
function resetQuestion(){questionForm.value={id:0,question_type:'single_choice',stem:'',standard_answer:'',options_text:'A|选项A\nB|选项B',max_score:5};standardSelections.value=[]}
function editQuestion(q:any){questionForm.value={id:q.id,question_type:q.question_type,stem:q.stem,standard_answer:q.standard_answer||'',options_text:(q.options||[]).filter((x:any)=>q.question_type!=='true_false').map((x:any)=>`${optionLabel(x)}|${x.content}`).join('\n'),max_score:Number(q.max_score)};standardSelections.value=q.question_type==='multiple_choice'?String(q.standard_answer||'').split(/[,，\s]+/).filter(Boolean):[];document.getElementById('question-editor')?.scrollIntoView({behavior:'smooth'})}
async function saveQuestion(){if(!selected.value||!questionForm.value.stem.trim())return;loading.value=true;try{const standard=questionForm.value.question_type==='multiple_choice'?standardSelections.value.join(','):questionForm.value.standard_answer;const payload={question_type:questionForm.value.question_type,stem:questionForm.value.stem,standard_answer:standard,options:parseOptions(),max_score:questionForm.value.max_score};if(questionForm.value.id)await api.patch(`/questions/${questionForm.value.id}`,payload);else await api.post(`/assignments/${selected.value.id}/questions`,payload);message.value=questionForm.value.id?'题目修改成功':'题目添加成功，空缺的标准答案已由 AI 自动补充';resetQuestion();await openAssignment(selected.value.id)}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function generateMaterials(){if(!selected.value||!materialForm.value.document_id)return;loading.value=true;try{const data=(await api.post(`/assignments/${selected.value.id}/generate-materials`,materialForm.value)).data;message.value=`已根据《${data.document_name}》生成 ${data.created} 项材料`;await openAssignment(selected.value.id)}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function publish(){try{await api.post(`/assignments/${selected.value.id}/publish`);message.value='作业已发布';await openAssignment(selected.value.id);await load()}catch(e:any){error.value=e.message}}
async function submit(){loading.value=true;try{const data=(await api.post(`/assignments/${selected.value.id}/submissions`,{answers:selected.value.questions.map((q:any)=>({question_id:q.id,answer:answers.value[q.id]??''}))})).data;message.value=`作业已提交并即时批改，当前建议得分 ${data.total_score}`;await openAssignment(selected.value.id);await openSubmission(data.id);await load()}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function openSubmission(id:number){try{selectedSubmission.value=(await api.get(`/submissions/${id}`)).data}catch(e:any){error.value=e.message}}
async function grade(id:number){loading.value=true;try{await api.post(`/submissions/${id}/grade`);message.value='AI 辅助批改完成'}catch(e:any){if(!e.message.includes('已经生成'))error.value=e.message}finally{await openSubmission(id);loading.value=false}}
async function review(result:any){try{await api.patch(`/grading-results/${result.id}/review`,{final_score:Number(result.final_score??result.suggested_score),feedback:result.feedback});message.value='该题复核完成';await openSubmission(selectedSubmission.value.id);submissions.value=(await api.get(`/assignments/${selected.value.id}/submissions`)).data}catch(e:any){error.value=e.message}}
onActivated(()=>load().catch(e=>error.value=e.message))
</script>

<template>
  <div class="page">
    <div class="page-title"><div><h1>{{isTeacher?'作业管理中心':'我的作业'}}</h1><p>{{isTeacher?'创建、编辑、发布作业并复核即时批改结果。':'提交后立即查看批改建议和标准答案。'}}</p></div><button v-if="isTeacher" @click="tab=tab==='create'?'list':'create'">{{tab==='create'?'返回列表':'＋ 创建作业'}}</button></div>
    <div v-if="error" class="notice error">{{error}} <button class="text-button" @click="error=''">关闭</button></div>
    <div v-if="message" class="notice success-box">{{message}} <button class="text-button" @click="message=''">关闭</button></div>

    <div v-if="tab==='create'&&isTeacher" class="card">
      <h2>创建作业草稿</h2><div class="form-grid"><label>发布课程<select v-model.number="assignmentForm.course_id"><option v-for="c in courses" :value="c.id">{{c.name}}</option></select></label><label>作业标题<input v-model="assignmentForm.title"></label><label>截止时间<input type="datetime-local" v-model="assignmentForm.due_at"></label></div><label>作业说明<textarea v-model="assignmentForm.description"/></label><button :disabled="loading" @click="createAssignment">创建并添加题目</button>
    </div>

    <div v-if="tab==='list'">
      <div v-if="!assignments.length" class="card empty">暂无作业</div>
      <section v-for="group in groupedAssignments" :key="group.course_id" class="card assignment-group"><div class="section-header"><h2>{{group.course_name}}</h2><span class="badge">{{group.items.length}} 项</span></div><div class="assignment-list"><article v-for="a in group.items" :key="a.id" class="assignment-card" @click="openAssignment(a.id)"><span :class="['status',a.status]">{{a.status}}</span><h3>{{a.title}}</h3><p>{{a.description||'暂无作业说明'}}</p><div class="assignment-meta"><span>总分 {{a.total_score}}</span><span>{{a.question_count}} 题</span><span v-if="isTeacher">{{a.submission_count}} 人提交</span><span>截止 {{a.due_at?new Date(a.due_at).toLocaleString():'不限'}}</span></div><button class="secondary">查看作业</button></article></div></section>
    </div>

    <div v-if="tab==='detail'&&selected" class="detail-layout">
      <div class="card">
        <button class="back" @click="tab='list';selected=null">← 返回作业列表</button><div class="section-header"><div><span class="eyebrow">{{selected.course_name}}</span><h2>{{selected.title}}</h2><p>{{selected.description}}</p></div><span :class="['status',selected.status]">{{selected.status}}</span></div><div class="assignment-meta"><span>总分 {{selected.total_score}}</span><span>{{selected.question_count}} 道题</span></div>
        <div v-for="(q,index) in selected.questions" :key="q.id" class="question"><div class="question-title"><strong>{{index+1}}. {{q.stem}}</strong><span>{{q.max_score}} 分</span></div><div v-if="q.options?.length" class="options"><label v-for="o in q.options"><input :type="q.question_type==='multiple_choice'?'checkbox':'radio'" :name="`q${q.id}`" :value="optionLabel(o)" v-model="answers[q.id]">{{optionLabel(o)}}. {{o.content}}</label></div><textarea v-else-if="!isTeacher&&!selected.my_submission" v-model="answers[q.id]" placeholder="请输入答案"></textarea><div v-if="isTeacher" class="answer-key"><span>参考答案：{{q.standard_answer}}</span> <button v-if="!submissions.length" class="secondary" @click="editQuestion(q)">修改题目</button></div></div>

        <template v-if="isTeacher">
          <button v-if="selected.status==='draft'&&selected.questions.length" @click="publish">发布作业</button>
          <div v-if="!submissions.length" class="question-builder">
            <h3>AI 从知识库生成材料</h3><div v-if="!documents.length" class="empty">该课程知识库暂无可用文件</div><template v-else><label>参考文件<select v-model.number="materialForm.document_id"><option v-for="d in documents" :value="d.id">{{d.filename}}</option></select></label><label>章节或主题<input v-model="materialForm.chapter_or_topic"></label><div class="form-grid"><label>课堂例题数<input type="number" min="0" max="5" v-model.number="materialForm.example_count"></label><label>练习题数<input type="number" min="0" max="10" v-model.number="materialForm.exercise_count"></label><label>思考题数<input type="number" min="0" max="5" v-model.number="materialForm.thinking_count"></label><label>拓展材料数<input type="number" min="0" max="5" v-model.number="materialForm.extension_count"></label></div><button :disabled="loading||!materialForm.chapter_or_topic" @click="generateMaterials">{{loading?'AI 正在生成…':'自动生成并加入作业'}}</button></template>
            <hr><div id="question-editor" class="section-header"><h3>{{questionForm.id?'修改已添加题目':'手动添加题目'}}</h3><button v-if="questionForm.id" class="ghost" @click="resetQuestion">取消修改</button></div><div class="form-grid"><label>题型<select v-model="questionForm.question_type"><option value="single_choice">单选题</option><option value="multiple_choice">多选题</option><option value="true_false">判断题</option><option value="short_answer">简答题</option><option value="essay">论述题</option></select></label><label>满分<input type="number" min="1" v-model.number="questionForm.max_score"></label></div><label>题干<textarea v-model="questionForm.stem"></textarea></label><label v-if="['single_choice','multiple_choice'].includes(questionForm.question_type)">选项（每行：编号|内容）<textarea v-model="questionForm.options_text"></textarea></label>
            <div v-if="questionForm.question_type==='single_choice'" class="options"><strong>正确选项（可留空由 AI 补充）</strong><label v-for="o in parseOptions()"><input type="radio" name="standard-single" :value="optionLabel(o)" v-model="questionForm.standard_answer">{{optionLabel(o)}}. {{o.content}}</label></div><div v-else-if="questionForm.question_type==='multiple_choice'" class="options"><strong>正确选项（可多选）</strong><label v-for="o in parseOptions()"><input type="checkbox" :value="optionLabel(o)" v-model="standardSelections">{{optionLabel(o)}}. {{o.content}}</label></div><div v-else-if="questionForm.question_type==='true_false'" class="options"><strong>判断答案</strong><label><input type="radio" name="standard-tf" value="true" v-model="questionForm.standard_answer">正确</label><label><input type="radio" name="standard-tf" value="false" v-model="questionForm.standard_answer">错误</label></div><label v-else>参考答案 <span class="field-help">可以留空，由 AI 根据课程知识库补充</span><textarea v-model="questionForm.standard_answer"></textarea></label><button :disabled="loading||!questionForm.stem.trim()" @click="saveQuestion">{{questionForm.id?'保存题目修改':'添加题目'}}</button>
          </div>
        </template>
        <button v-else-if="selected.status==='published'&&!selected.my_submission" :disabled="loading" @click="submit">{{loading?'正在提交并批改…':'提交并立即批改'}}</button><div v-else-if="selected.my_submission" class="submitted-panel">已提交，状态：{{selected.my_submission.status}} <button class="secondary" @click="openSubmission(selected.my_submission.id)">查看批改与标准答案</button></div>
      </div>
      <aside v-if="isTeacher" class="card submission-panel"><h2>学生提交 <span class="badge">{{submissions.length}}</span></h2><div v-if="!submissions.length" class="empty">暂无学生提交</div><button v-for="s in submissions" :key="s.id" class="submission-item" @click="openSubmission(s.id)"><span><strong>{{s.student_name}}</strong><small>{{new Date(s.submitted_at).toLocaleString()}}</small></span><span :class="['status',s.status]">{{s.status}}</span></button></aside>
    </div>

    <div v-if="selectedSubmission" class="modal-backdrop" @click.self="selectedSubmission=null"><div class="modal wide"><button class="modal-close" @click="selectedSubmission=null">×</button><h2>提交与即时批改结果</h2><p>建议总分：{{selectedSubmission.total_score}} · 主观题结果仍可由教师复核</p><div v-for="(answer,index) in selectedSubmission.answers" class="review-answer"><strong>第 {{index+1}} 题作答</strong><p>{{Array.isArray(answer.answer)?answer.answer.join('、'):answer.answer}}</p><div v-for="r in selectedSubmission.grading_results.filter((x:any)=>x.question_id===answer.question_id)" class="grading-box"><p><strong>标准答案：</strong>{{r.standard_answer}}</p><p><strong>批改反馈：</strong>{{r.feedback}}</p><span>建议得分：{{r.suggested_score}} · 置信度：{{r.confidence}}</span><template v-if="isTeacher"><label>最终得分<input type="number" v-model.number="r.final_score" :placeholder="String(r.suggested_score)"></label><label>教师评语<textarea v-model="r.feedback"></textarea></label><button v-if="r.status!=='approved'" @click="review(r)">确认该题评分</button></template></div></div><button v-if="isTeacher&&!selectedSubmission.grading_results.length" :disabled="loading" @click="grade(selectedSubmission.id)">启动 AI 辅助批改</button></div></div>
  </div>
</template>
