<script setup lang="ts">
import{computed,onActivated,ref,watch}from'vue'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'
const auth=useAuthStore(),isTeacher=computed(()=>['teacher','admin'].includes(auth.user?.role||''))
const courses=ref<any[]>([]),courseId=ref(Number(sessionStorage.getItem('qa_course_id'))||0),sessions=ref<any[]>([]),sessionId=ref<number>(),question=ref(''),history=ref<any[]>([]),error=ref(''),loading=ref(false)
async function load(){courses.value=(await api.get(isTeacher.value?'/courses/managed':'/courses')).data;if(!courses.value.some(x=>x.id===courseId.value)&&courses.value.length)courseId.value=courses.value[0].id}
async function loadSessions(){if(!courseId.value)return;sessions.value=(await api.get(`/qa/sessions?course_id=${courseId.value}`)).data;if(sessions.value.length)await selectSession(sessions.value[0].id);else{sessionId.value=undefined;history.value=[]}}
async function selectSession(id:number){sessionId.value=id;history.value=(await api.get(`/qa/sessions/${id}/messages`)).data}
function newChat(){sessionId.value=undefined;history.value=[];question.value=''}
watch(courseId,async()=>{sessionStorage.setItem('qa_course_id',String(courseId.value));await loadSessions().catch((e:any)=>error.value=e.message)})
async function ask(){if(!question.value.trim()||!courseId.value)return;loading.value=true;error.value='';const userText=question.value;history.value.push({role:'user',content:userText});question.value='';try{if(!sessionId.value){sessionId.value=(await api.post('/qa/sessions',{course_id:courseId.value,title:userText.slice(0,28)})).data.id;sessions.value.unshift({id:sessionId.value,title:userText.slice(0,28)})}const data=(await api.post(`/qa/sessions/${sessionId.value}/messages`,{content:userText})).data;history.value.push({role:'assistant',content:data.answer,citations:data.citations,confidence:data.confidence,insufficient:data.insufficient_evidence})}catch(e:any){history.value.pop();question.value=userText;error.value=e.message}finally{loading.value=false}}
onActivated(async()=>{try{await load();await loadSessions()}catch(e:any){error.value=e.message}})
</script>
<template><div class="page chat-page"><div class="page-title"><div><h1>课堂智能答疑</h1><p>对话会自动保留；回答依据当前课程知识库并附带资料来源。</p></div><label class="course-picker">答疑课程<select v-model.number="courseId"><option v-for="c in courses" :value="c.id">{{c.name}} · {{c.subject}}</option></select></label></div><div v-if="!courses.length" class="card empty">暂无可用课程，请先加入课程</div><div v-else class="ai-chat-shell"><aside class="chat-sidebar"><button @click="newChat">＋ 新对话</button><h3>最近对话</h3><button v-for="s in sessions" :class="['session-button',{active:s.id===sessionId}]" @click="selectSession(s.id)">{{s.title}}</button></aside><section class="chat-main"><div class="chat-history"><div v-if="!history.length" class="chat-welcome"><span>AI</span><h2>有什么课程问题需要一起解决？</h2><p>我会优先检索课程资料；证据不足时会明确提示由教师确认。</p></div><div v-for="item in history" :class="['chat-message',item.role]"><div class="avatar">{{item.role==='user'?'我':'AI'}}</div><div class="message-body"><div class="bubble">{{item.content}}</div><div v-if="item.corrected_at" class="teacher-correction">✓ 此回答已由教师修正<span v-if="item.correction_note">：{{item.correction_note}}</span></div><div v-if="item.citations?.length" class="chat-citations"><span v-for="c in item.citations">{{c.filename}} · 第 {{c.chunk_index+1}} 块</span></div><small v-if="item.role==='assistant'">置信度 {{Math.round((item.confidence||0)*100)}}% <b v-if="item.insufficient">· 建议转交教师</b></small></div></div><div v-if="loading" class="typing">AI 正在检索课程资料…</div></div><div class="chat-compose"><textarea v-model="question" placeholder="向课程 AI 提问……" @keydown.ctrl.enter="ask"></textarea><button :disabled="loading||!question.trim()" @click="ask">发送</button><p class="error">{{error}}</p><small>Ctrl + Enter 发送 · AI 回答可能需要教师确认</small></div></section></div></div></template>
