<script setup lang="ts">
import{computed,nextTick,onActivated,ref,watch}from'vue'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'
const auth=useAuthStore(),isTeacher=computed(()=>['teacher','admin'].includes(auth.user?.role||''))
const courses=ref<any[]>([]),courseId=ref(Number(sessionStorage.getItem('qa_course_id'))||0),sessions=ref<any[]>([]),sessionId=ref<number>(),question=ref(''),history=ref<any[]>([]),error=ref(''),loading=ref(false),editingId=ref<number>(),editingTitle=ref(''),chatBox=ref<HTMLDivElement>()
function toBottom(){nextTick(()=>{const el=chatBox.value;if(el)el.scrollTop=el.scrollHeight})}
async function load(){courses.value=(await api.get(isTeacher.value?'/courses/managed':'/courses')).data;if(!courses.value.some(x=>x.id===courseId.value)&&courses.value.length)courseId.value=courses.value[0].id}
async function loadSessions(){if(!courseId.value)return;sessions.value=(await api.get(`/qa/sessions?course_id=${courseId.value}`)).data;if(sessions.value.length)await selectSession(sessions.value[0].id);else newChat()}
async function selectSession(id:number){sessionId.value=id;history.value=(await api.get(`/qa/sessions/${id}/messages`)).data;toBottom()}
function newChat(){sessionId.value=undefined;history.value=[];question.value='';editingId.value=undefined}
function startRename(session:any){editingId.value=session.id;editingTitle.value=session.title}
async function saveRename(session:any){const title=editingTitle.value.trim();if(!title)return;try{const data=(await api.patch(`/qa/sessions/${session.id}`,{title})).data;session.title=data.title;editingId.value=undefined}catch(e:any){error.value=e.message}}
watch(courseId,async()=>{sessionStorage.setItem('qa_course_id',String(courseId.value));await loadSessions().catch((e:any)=>error.value=e.message)})
async function ask(){if(!question.value.trim()||!courseId.value)return;loading.value=true;error.value='';const userText=question.value;history.value.push({role:'user',content:userText});question.value='';toBottom();try{if(!sessionId.value){const created=(await api.post('/qa/sessions',{course_id:courseId.value,title:userText.slice(0,28)})).data;sessionId.value=created.id;sessions.value.unshift({id:created.id,title:created.title})}const data=(await api.post(`/qa/sessions/${sessionId.value}/messages`,{content:userText})).data;history.value.push({role:'assistant',content:data.answer,citations:data.citations,confidence_level:data.confidence_level,insufficient:data.insufficient_evidence,fallback:data.fallback});toBottom()}catch(e:any){history.value.pop();question.value=userText;error.value=e.message}finally{loading.value=false}}
onActivated(async()=>{try{await load();await loadSessions()}catch(e:any){error.value=e.message}})
</script>
<template><div class="page chat-page"><div class="page-title"><div><h1>课堂智能答疑</h1><p>对话会自动保留；优先使用课程知识库，必要时以公开网页补充并标明来源。</p></div></div><div v-if="!courses.length" class="card empty">暂无可用课程，请先加入课程</div><div v-else class="ai-chat-shell"><aside class="chat-sidebar"><label class="chat-course-picker">答疑课程<select v-model.number="courseId"><option v-for="c in courses" :key="c.id" :value="c.id">{{c.name}} · {{c.subject}}</option></select></label><button class="new-chat-button" @click="newChat">＋ 新对话</button><h3>最近对话</h3><div v-for="s in sessions" :key="s.id" :class="['session-row',{active:s.id===sessionId}]"><template v-if="editingId===s.id"><input v-model="editingTitle" maxlength="255" @keyup.enter="saveRename(s)" @keyup.esc="editingId=undefined"><button title="保存名称" @click="saveRename(s)">✓</button></template><template v-else><button class="session-button" @click="selectSession(s.id)">{{s.title}}</button><button class="rename-session" title="修改对话名称" @click="startRename(s)">✎</button></template></div></aside><section class="chat-main"><div ref="chatBox" class="chat-history"><div v-if="!history.length" class="chat-welcome"><span>AI</span><h2>有什么课程问题需要一起解决？</h2><p>我会优先检索课程资料，资料不足时补充公开网页；所有网页来源都可点击核对。</p></div><div v-for="item in history" :class="['chat-message',item.role]"><div class="avatar">{{item.role==='user'?'我':'AI'}}</div><div class="message-body"><div class="bubble">{{item.content}}</div><div v-if="item.corrected_at" class="teacher-correction">✓ 此回答已由教师修正<span v-if="item.correction_note">：{{item.correction_note}}</span></div><div v-if="item.citations?.length" class="chat-citations"><template v-for="c in item.citations" :key="`${c.source_type||'kb'}-${c.chunk_id||c.source_url}`"><a v-if="c.source_url" :href="c.source_url" target="_blank" rel="noopener noreferrer"><b>{{c.source_type==='web'?'网络补充':'课程资料'}}</b> · {{c.filename}}<template v-if="c.source_type!=='web'"> · 第 {{c.chunk_index+1}} 块</template></a><span v-else><b>课程资料</b> · {{c.filename}} · 第 {{c.chunk_index+1}} 块</span></template></div><small v-if="item.role==='assistant'">置信度：<span :style="{color:item.confidence_level==='高'?'#16804b':item.confidence_level==='较高'?'#856000':'#b45f06',fontWeight:'600'}">{{item.confidence_level||'中'}}</span><b v-if="item.insufficient"> · 建议转交教师</b></small></div></div><div v-if="loading" class="typing">AI 正在检索课程资料与可用网络来源…</div></div><div class="chat-compose"><textarea v-model="question" placeholder="向课程 AI 提问……" @keydown.ctrl.enter="ask"></textarea><button :disabled="loading||!question.trim()" @click="ask">发送</button><p class="error">{{error}}</p><small>Ctrl + Enter 发送 · AI 回答可能需要教师确认</small></div></section></div></div></template>
