<script setup lang="ts">
import{computed,onActivated,ref,watch}from'vue'
import{useRoute}from'vue-router'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'
const auth=useAuthStore(),route=useRoute(),courses=ref<any[]>([]),courseId=ref(Number(route.query.course)||0),category=ref('textbook'),files=ref<File[]>([]),documents=ref<any[]>([]),query=ref(''),result=ref<any[]>([]),batch=ref<any>(),message=ref(''),loading=ref(false)
const canUpload=computed(()=>['teacher','admin'].includes(auth.user?.role||'')&&Boolean(courses.value.find(c=>c.id===courseId.value)?.is_manager))
async function loadCourses(){courses.value=(await api.get('/courses')).data;if(!courseId.value&&courses.value.length)courseId.value=courses.value[0].id}
async function loadDocuments(){if(!courseId.value){documents.value=[];return}documents.value=(await api.get(`/courses/${courseId.value}/documents`)).data}
function selectFiles(event:Event){files.value=Array.from((event.target as HTMLInputElement).files||[])}
async function upload(){if(!files.value.length)return;loading.value=true;message.value='';const form=new FormData();form.append('category',category.value);files.value.forEach(file=>form.append('files',file));try{batch.value=(await api.post(`/courses/${courseId.value}/documents/batch`,form)).data;message.value=`上传完成：成功 ${batch.value.uploaded}，重复 ${batch.value.duplicates}，失败 ${batch.value.failed}`;files.value=[];await loadDocuments()}catch(e:any){message.value=e.message}finally{loading.value=false}}
async function search(){if(!query.value.trim())return;loading.value=true;try{result.value=(await api.post('/knowledge/search',{course_id:courseId.value,query:query.value,top_k:8})).data}catch(e:any){message.value=e.message}finally{loading.value=false}}
watch(courseId,()=>{loadDocuments().catch(e=>message.value=e.message);result.value=[]})
onActivated(async()=>{try{await loadCourses();await loadDocuments()}catch(e:any){message.value=e.message}})
</script>
<template><div class="page"><div class="page-title"><div><h1>课程知识库</h1><p>{{canUpload?'批量上传教材，系统按文件内容自动去重并建立索引。':'查看教师上传的课程资料并进行知识检索。'}}</p></div><label class="course-picker">当前课程<select v-model.number="courseId"><option v-for="c in courses" :value="c.id">{{c.name}}</option></select></label></div><div v-if="canUpload" class="card"><h2>批量上传学习文件</h2><div class="upload-zone"><input id="multi-files" type="file" multiple accept=".txt,.md,.pdf,.docx" @change="selectFiles"><label for="multi-files"><strong>点击选择多个文件</strong><span>支持 TXT、Markdown、PDF、DOCX；单次最多 20 个</span></label></div><div v-if="files.length" class="selected-files"><span v-for="f in files" :key="f.name">{{f.name}} · {{(f.size/1024).toFixed(1)}}KB</span></div><div class="inline-actions"><select v-model="category"><option value="textbook">教材</option><option value="courseware">课件</option><option value="question_bank">题库</option></select><button :disabled="loading||!files.length" @click="upload">{{loading?'处理中…':`上传 ${files.length||''} 个文件`}}</button></div><p>{{message}}</p><div v-if="batch" class="batch-results"><div v-for="x in batch.results" :class="['upload-result',x.status]"><strong>{{x.filename}}</strong><span>{{x.status==='ready'?'上传成功':x.status==='duplicate'?x.message:x.error}}</span></div></div></div><div class="card"><h2>知识库文件 <span class="badge">{{documents.length}}</span></h2><div v-if="!documents.length" class="empty">当前课程尚未上传资料</div><div class="document-table" v-else><div class="document-row heading"><span>文件名</span><span>类型</span><span>分块</span><span>状态</span><span>上传时间</span></div><div class="document-row" v-for="doc in documents" :key="doc.id"><span class="document-name">📄 {{doc.filename}}</span><span>{{doc.category}}</span><span>{{doc.chunks}}</span><span :class="['status',doc.status]">{{doc.status}}</span><span>{{new Date(doc.created_at).toLocaleString()}}</span></div></div></div><div class="card"><h2>知识检索</h2><div class="search-bar"><input v-model="query" placeholder="例如：过拟合有哪些解决方法？" @keyup.enter="search"><button :disabled="loading" @click="search">检索</button></div><div v-for="x in result" :key="x.chunk_id" class="search-result"><div><strong>{{x.filename}}</strong><span>第 {{x.chunk_index+1}} 块 · 相关度 {{x.rerank_score?.toFixed(2)}}</span></div><p>{{x.content}}</p></div></div></div></template>
