<script setup lang="ts">
import{onMounted,reactive,ref}from'vue'
import{api}from'../api/client'

const loading=ref(false),testing=ref(false),message=ref(''),error=ref(''),testResult=ref<any>()
const form=reactive<any>({
  llm_provider:'ollama',llm_base_url:'http://localhost:11434',llm_model:'qwen2.5:latest',llm_api_key:'',llm_temperature:null,clear_llm_api_key:false,llm_api_key_configured:false,
  embedding_provider:'ollama',embedding_base_url:'http://localhost:11434',embedding_model:'embeddinggemma:latest',embedding_api_key:'',clear_embedding_api_key:false,embedding_api_key_configured:false,
  embedding_dimension:768,vector_collection:'edu_chunks_dev',keep_alive:'-1'
})
function payload(){const{llm_api_key_configured,embedding_api_key_configured,...value}=form;return value}
async function load(){loading.value=true;error.value='';try{Object.assign(form,(await api.get('/admin/model-settings')).data,{llm_api_key:'',embedding_api_key:'',clear_llm_api_key:false,clear_embedding_api_key:false})}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function testConnection(){testing.value=true;error.value='';message.value='';testResult.value=undefined;try{testResult.value=(await api.post('/admin/model-settings/test',payload())).data;message.value='LLM 与 Embedding 连接测试均已通过'}catch(e:any){error.value=e.message}finally{testing.value=false}}
async function save(){loading.value=true;error.value='';message.value='';try{const data=(await api.put('/admin/model-settings',payload())).data;Object.assign(form,data,{llm_api_key:'',embedding_api_key:'',clear_llm_api_key:false,clear_embedding_api_key:false});message.value='模型配置已加密保存，新请求将立即使用该配置；重启后仍然有效。'}catch(e:any){error.value=e.message}finally{loading.value=false}}
onMounted(load)
</script>
<template><div class="page model-settings-page"><div class="page-title"><div><h1>模型服务设置</h1><p>管理员可切换本地 Ollama 或 OpenAI 兼容 API，并为 LLM 与 Embedding 分别指定模型。</p></div></div><p v-if="error" class="notice error">{{error}}</p><p v-if="message" class="notice success-box">{{message}}</p>
<div class="model-settings-grid"><section class="card provider-card"><h2>大语言模型（LLM）</h2><label>服务类型<select v-model="form.llm_provider"><option value="ollama">本地 Ollama</option><option value="openai_compatible">OpenAI 兼容 API</option></select></label><label>服务地址<input v-model.trim="form.llm_base_url" placeholder="Ollama: http://localhost:11434；API: https://example.com/v1"></label><label>模型名称<input v-model.trim="form.llm_model" placeholder="例如 qwen2.5:latest 或 deepseek-chat"></label><label>温度 <span class="muted">(留空使用服务默认值)</span><input v-model.number="form.llm_temperature" type="number" min="0" max="2" step="0.1" placeholder="例如 1.0"></label><label v-if="form.llm_provider==='openai_compatible'">API Key <span v-if="form.llm_api_key_configured" class="badge">已加密配置</span><input v-model="form.llm_api_key" type="password" autocomplete="new-password" :placeholder="form.llm_api_key_configured?'留空表示保留现有 Key':'输入 API Key'"></label><label v-if="form.llm_api_key_configured" class="checkbox-line"><input v-model="form.clear_llm_api_key" type="checkbox">清除已保存的 LLM API Key</label><label v-if="form.llm_provider==='ollama'">模型驻留时间<input v-model.trim="form.keep_alive" placeholder="-1 表示持续驻留"></label><p class="provider-help">OpenAI 兼容服务需提供 <code>/chat/completions</code> 与 <code>/models</code>。地址通常应包含服务商要求的 <code>/v1</code> 前缀。</p></section>
<section class="card provider-card"><h2>向量模型（Embedding）</h2><label>服务类型<select v-model="form.embedding_provider"><option value="ollama">本地 Ollama</option><option value="openai_compatible">OpenAI 兼容 API</option></select></label><label>服务地址<input v-model.trim="form.embedding_base_url" placeholder="Ollama: http://localhost:11434；API: https://example.com/v1"></label><label>模型名称<input v-model.trim="form.embedding_model" placeholder="例如 embeddinggemma:latest"></label><label v-if="form.embedding_provider==='openai_compatible'">API Key <span v-if="form.embedding_api_key_configured" class="badge">已加密配置</span><input v-model="form.embedding_api_key" type="password" autocomplete="new-password" :placeholder="form.embedding_api_key_configured?'留空表示保留现有 Key':'输入 API Key'"></label><label v-if="form.embedding_api_key_configured" class="checkbox-line"><input v-model="form.clear_embedding_api_key" type="checkbox">清除已保存的 Embedding API Key</label><div class="form-grid"><label>向量维度<input v-model.number="form.embedding_dimension" type="number" min="1" max="65536"></label><label>Milvus collection<input v-model.trim="form.vector_collection" placeholder="edu_chunks_dev"></label></div><p class="provider-help">连接测试会核对实际向量维度。更换 Embedding 模型时建议使用新的 collection 名称；旧资料需要重新建立向量索引，否则只能使用关键词检索。</p></section></div>
<section class="card"><div class="model-settings-actions"><button :disabled="testing||loading" @click="testConnection">{{testing?'测试中…':'测试两项连接'}}</button><button :disabled="loading||testing" @click="save">{{loading?'保存中…':'保存并应用'}}</button><span class="muted">建议先测试，再保存。API Key 只会加密写入本机 storage，不会返回前端。</span></div><div v-if="testResult" class="connection-result">LLM：{{testResult.llm.provider}} / {{testResult.llm.model}}；Embedding：{{testResult.embedding.provider}} / {{testResult.embedding.model}} / {{testResult.embedding.dimension}} 维</div></section></div></template>
