<script setup lang="ts">
import {computed,onActivated,ref,watch} from 'vue'
import {api} from '../api/client'
import {useAuthStore} from '../stores/auth'
const auth=useAuthStore(),courses=ref<any[]>([]),students=ref<any[]>([]),reports=ref<any[]>([]),result=ref<any>(),error=ref(''),message=ref(''),loading=ref(false)
const isParent=computed(()=>auth.user?.role==='parent')
const form=ref({student_id:1,course_id:0,period_type:'week',period_start:new Date(Date.now()-604800000).toISOString(),period_end:new Date().toISOString()})
function asList(value:any):string[]{if(Array.isArray(value))return value.map(String);if(typeof value==='string')return value.split(/[\n；;]+/).map(x=>x.trim()).filter(Boolean);return value?[String(value)]:[]}
function asText(value:any):string{return Array.isArray(value)?value.join('；'):String(value||'')}
async function load(){if(isParent.value){students.value=(await api.get('/parent/students')).data;if(students.value.length&&!students.value.some(x=>x.id===form.value.student_id))form.value.student_id=students.value[0].id;await loadParentReports()}else{courses.value=(await api.get('/courses/managed')).data;if(courses.value.length&&!form.value.course_id)form.value.course_id=courses.value[0].id}}
async function loadParentReports(){if(form.value.student_id)reports.value=(await api.get(`/parent/reports?student_id=${form.value.student_id}`)).data}
async function loadStudents(){if(!form.value.course_id||isParent.value)return;students.value=(await api.get(`/courses/${form.value.course_id}/students`)).data;if(students.value.length)form.value.student_id=students.value[0].id}
async function run(){loading.value=true;error.value='';try{result.value=(await api.post('/reports/generate',form.value)).data;message.value='报告草稿生成成功，请核对后发布'}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function publish(){try{await api.patch(`/reports/${result.value.id}/review`,{action:'publish',comment:'教师审核通过'});result.value.status='published';message.value='报告已发布'}catch(e:any){error.value=e.message}}
watch(()=>form.value.course_id,()=>loadStudents().catch((e:any)=>error.value=e.message));watch(()=>form.value.student_id,()=>{if(isParent.value)loadParentReports().catch((e:any)=>error.value=e.message)})
onActivated(async()=>{try{await load();await loadStudents()}catch(e:any){error.value=e.message}})
</script>

<template><div class="page"><div class="page-title"><div><h1>{{isParent?'孩子的学习报告':'学习报告管理'}}</h1><p>{{isParent?'按孩子查看教师已审核的家长友好报告。':'依据真实学习数据生成并审核报告。'}}</p></div><label v-if="isParent" class="course-picker">当前孩子<select v-model.number="form.student_id"><option v-for="s in students" :value="s.id">{{s.display_name}}（{{s.username}}）</option></select></label></div><p v-if="error" class="notice error">{{error}}</p><p v-if="message" class="notice success-box">{{message}}</p>
<template v-if="isParent"><div v-if="!students.length" class="card empty">当前家长账号尚未绑定学生</div><div v-else-if="!reports.length" class="card empty">该学生暂无已发布报告</div><article v-for="r in reports" :key="r.id" class="card report-card"><div class="section-header"><h2>{{r.period_type==='week'?'学习周报':'学习月报'}}</h2><span class="status published">已发布</span></div><div class="grid report-metrics"><div><strong>整体掌握情况</strong><div class="metric">{{Math.round((r.metrics.average_mastery||0)*100)}}%</div></div><div><strong>有数据的知识点</strong><div class="metric">{{r.metrics.knowledge_points}}</div></div></div><h3>本阶段概况</h3><p>{{asText(r.content.overview||r.content.summary)}}</p><h3>值得肯定</h3><ul><li v-for="x in asList(r.content.highlights||r.content.progress)">{{x}}</li></ul><h3>接下来重点关注</h3><ul><li v-for="x in asList(r.content.needs_attention||r.content.weaknesses)">{{x}}</li></ul><h3>在家可以这样配合</h3><ol><li v-for="x in asList(r.content.action_plan||r.content.suggestions)">{{x}}</li></ol><p class="encouragement">{{asText(r.content.encouragement)}}</p><p class="muted">{{asText(r.content.metrics_explanation)}}</p></article></template>
<template v-else><div class="card"><h2>生成报告</h2><div class="form-grid"><label>课程<select v-model.number="form.course_id"><option v-for="c in courses" :value="c.id">{{c.name}}</option></select></label><label>学生<select v-model.number="form.student_id"><option v-for="s in students" :value="s.id">{{s.display_name}}</option></select></label><label>周期<select v-model="form.period_type"><option value="week">周报</option><option value="month">月报</option></select></label></div><button v-if="students.length" :disabled="loading" @click="run">{{loading?'生成中…':'生成待审核报告'}}</button><div v-else class="empty">该课程暂无学生</div></div><div v-if="result" class="card report-card"><div class="section-header"><h2>家长端报告预览</h2><span :class="['status',result.status]">{{result.status}}</span></div><h3>本阶段概况</h3><p>{{asText(result.content.overview)}}</p><h3>值得肯定</h3><ul><li v-for="x in asList(result.content.highlights)">{{x}}</li></ul><h3>需要关注</h3><ul><li v-for="x in asList(result.content.needs_attention)">{{x}}</li></ul><h3>家庭行动建议</h3><ol><li v-for="x in asList(result.content.action_plan)">{{x}}</li></ol><p class="encouragement">{{asText(result.content.encouragement)}}</p><p class="muted">{{asText(result.content.metrics_explanation)}}</p><button v-if="result.status!=='published'" @click="publish">审核并发布</button></div></template></div></template>
