<script setup lang="ts">
import{onActivated,ref,watch}from'vue'
import{api}from'../api/client'
const courses=ref<any[]>([]),courseId=ref(0),records=ref<any[]>([]),summary=ref<any>({student_questions:[],wrong_answer_topics:[],focus:[]}),editing=ref<any>(),answer=ref(''),note=ref(''),error=ref(''),message=ref('')
async function loadCourses(){courses.value=(await api.get('/courses/managed')).data;if(courses.value.length&&!courseId.value)courseId.value=courses.value[0].id}
async function load(){if(!courseId.value)return;error.value='';const [review,frequency]=await Promise.all([api.get(`/courses/${courseId.value}/qa-review`),api.get(`/courses/${courseId.value}/high-frequency`)]);records.value=review.data;summary.value=frequency.data}
function edit(item:any){editing.value=item;answer.value=item.answer||'';note.value=item.correction_note||''}
async function save(){if(!editing.value?.answer_id||!answer.value.trim())return;try{await api.patch(`/qa/messages/${editing.value.answer_id}/correct`,{content:answer.value,note:note.value||null});message.value='修正已保存，系统已通知提问学生';editing.value=undefined;await load()}catch(e:any){error.value=e.message}}
watch(courseId,()=>load().catch((e:any)=>error.value=e.message))
onActivated(()=>loadCourses().catch((e:any)=>error.value=e.message))
</script>
<template><div class="page"><div class="page-title"><div><h1>课堂运营</h1><p>查看学生提问与 AI 回答，修正回答，并从提问和错题中发现课堂重点。</p></div><label class="course-picker">我参与的课程<select v-model.number="courseId"><option v-for="c in courses" :value="c.id">{{c.name}} · {{c.subject}}</option></select></label></div><p v-if="error" class="notice error">{{error}}</p><p v-if="message" class="notice success-box">{{message}}</p><div v-if="!courses.length" class="card empty">暂无有管理权限的课程</div><template v-else><section class="card"><div class="section-header"><h2>课堂高频问题与重点</h2><button class="ghost" @click="load">刷新汇总</button></div><div v-if="!summary.focus?.length" class="empty">积累学生提问和作业批改数据后，将自动形成课堂重点。</div><div v-else class="tag-list"><span v-for="x in summary.focus" class="focus-tag">{{x}}</span></div><div class="ops-columns"><div><h3>学生高频提问</h3><ol><li v-for="x in summary.student_questions">{{x.topic}} <b>× {{x.count}}</b></li></ol></div><div><h3>作业高频错题</h3><ol><li v-for="x in summary.wrong_answer_topics">{{x.topic}} <b>× {{x.count}}</b></li></ol></div></div></section><section class="card"><div class="section-header"><h2>学生答疑记录</h2><span>{{records.length}} 条</span></div><div v-if="!records.length" class="empty">当前课程暂无答疑记录</div><article v-for="item in records" :key="item.question_id" class="qa-review"><div class="qa-meta"><strong>{{item.student_name}}</strong><span>{{new Date(item.asked_at).toLocaleString()}}</span><span v-if="item.needs_teacher" class="status pending_review">需关注</span><span v-if="item.corrected_at" class="status published">教师已修正</span></div><h3>学生：{{item.question}}</h3><p class="answer-panel">AI：{{item.answer||'尚未生成回答'}}</p><small v-if="item.confidence!=null">置信度 {{Math.round(item.confidence*100)}}%</small><button v-if="item.answer_id" class="ghost" @click="edit(item)">审核并修正</button></article></section></template><div v-if="editing" class="modal-backdrop" @click.self="editing=undefined"><div class="card modal"><div class="section-header"><h2>修正 AI 回答</h2><button class="ghost" @click="editing=undefined">关闭</button></div><p><strong>学生问题：</strong>{{editing.question}}</p><label>修正后的完整回答<textarea v-model="answer" rows="8" placeholder="请输入准确、适合学生理解的回答"></textarea></label><label>修正说明（学生可理解）<input v-model="note" placeholder="例如：补充了适用条件，并修正第二步计算"></label><button @click="save">保存修正并通知学生</button></div></div></div></template>
